[package]
name = "compiler"
version = "0.1.0"
authors = ["davitz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substring = "1.4.5"
regex = "1"
lazy_static = "1"
arr_macro = "0"
